### ISSUE TITLE
--onboot=false does not work

### ISSUE THREAD

**Issue by yqin** [warewulf/warewulf#1101]
### Steps to reproduce

```
# wwctl node set n01 --netname eth0--netdev eth0 --onboot false -d -y
DEBUG  : Set log level to: 10, DEBUG
DEBUG  : Reading warewulf.conf from: /etc/warewulf/warewulf.conf
DEBUG  : sending following values: runtime overlay:
- ""
system overlay:
- ""
kernel: {}
ipmi:
  tagsdel:
  - ""
profiles:
- ""
network devices:
  um0:
    onboot: "true"
    device: um0
    tagsdel:
    - ""
tagsdel:
- ""
```

### Information on your system

```
# wwctl version
wwctl version:   4.5.0rc1-1
rpc version: apiPrefix:"rc1" apiVersion:"1" warewulfVersion:"4.5.0rc1-1"
# cat /etc/os-release
NAME="Rocky Linux"
VERSION="9.3 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.3"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.3 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2032-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.3"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.3"
```

### General information

- [X] I have run `wwctl version` and reported the contents of `/etc/os-release`
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have captured and reported relevant error messages and logs

**Comment by JasonYangShadow** [comment]
after checking the code, it turns out we should not set the bool value via this format
if you try setting `onboot` using this format

`--onboot=false`

```
[root@localhost warewulf]# wwctl node list
  NODE NAME  PROFILES  NETWORK  
  n1         default            
[root@localhost warewulf]# cat /usr/local/etc/warewulf/nodes.conf 
WW_INTERNAL: 45
nodeprofiles:
  default:
    comment: This profile is automatically included for each node
nodes:
  n1:
    profiles:
    - default
[root@localhost warewulf]# wwctl node set n1 --netname=eth0 --netdev=eth0 --onboot=false -y
[root@localhost warewulf]# cat /usr/local/etc/warewulf/nodes.conf 
WW_INTERNAL: 45
nodeprofiles:
  default:
    comment: This profile is automatically included for each node
nodes:
  n1:
    profiles:
    - default
    network devices:
      eth0:
        onboot: "false"
        device: eth0
```
