### ISSUE TITLE
document using locally-built ipxe using build-ipxe.sh

### ISSUE THREAD

**Issue by anderbubble** [warewulf/warewulf#1114]
Document how, why, and when to use `https://github.com/warewulf/warewulf/blob/main/scripts/build-ipxe.sh`, and how to configure Warewulf to use the iPXE builds that it generates.

**Comment by anderbubble** [comment]
From Slack:

One of the things we did for v4.5.0 was stop shipping an iPXE binary and start using the iPXE that comes with the host OS. Since then, we’ve encountered a few instances where the OS iPXE has bugs that were not present in the one we were shipping before, leading to unreliable behavior.

You might try building a new iPXE. We’ve got a script to help with that here: https://github.com/warewulf/warewulf/blob/main/scripts/build-ipxe.sh

That script will put new iPXE builds in `/usr/local/share/ipxe` by default. You’ll then need to configure Warewulf to use the iPXE builds from there. For example,

```
tftp:
  ipxe:
    "00:00": /usr/local/share/ipxe/undionly.kpxe
    "00:07": /usr/local/share/ipxe/ipxe-snponly-x86_64.efi
    "00:09": /usr/local/share/ipxe/ipxe-snponly-x86_64.efi
    00:0B: /usr/local/share/ipxe/arm64-efi/snponly.efi
```

After that, you’ll need to `rm /var/lib/tftpboot/warewulf/*` and `wwctl configure tftp`.

**Comment by alansill** [comment]
The current tftp section in our warewulf.conf reads as follows. Is it required to change the tftproot setting, or should we also remove the systemd name or alter how systemd calls or interacts with tftp?
```
tftp:
  enabled: true
  tftproot: /var/lib/tftpboot
  systemd name: tftp
  ipxe:
    "00:00": undionly.kpxe
    "00:07": ipxe-snponly-x86_64.efi
    "00:09": ipxe-snponly-x86_64.efi
    "00:0B": arm64-efi/snponly.efi
```

There is also a path in the paths area we could presumably change for ipxesource. Would that work and/or be cleaner?

```
paths:
  bindir: /usr/bin
  sysconfdir: /etc
  localstatedir: /var/lib
  ipxesource: /usr/share/ipxe
  srvdir: /var/lib
  firewallddir: /usr/lib/firewalld/services
  systemddir: /usr/lib/systemd/system
  wwoverlaydir: /var/lib/warewulf/overlays
  wwchrootdir: /var/lib/warewulf/chroots
  wwprovisiondir: /var/lib/warewulf/provision
  wwclientdir: /warewulf
```
