### ISSUE TITLE
Support = in tag values in wwctl <node|profile> set --tagadd

### ISSUE THREAD

**Issue by anderbubble** [warewulf/warewulf#1147]
### Summary

Support specifying a value with `--tagadd` that includes an equal sign, `=`.

### Rationale

When attempting to `wwctl profile set --yes --tagadd slurmdconf='Feature=standard CpuSpecList=1,33' standard`

We get an error:

```
ERROR: invalid argument "slurmdconf=Feature=standard CpuSpecList=1,33" for "--tagadd" flag: 33 must be formatted as key=value
```

These values can be entered into `nodes.conf` manually; but are not permitted by `wwctl`

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by anderbubble** [comment]
Transcribing @JasonYangShadow's comments from an internal ticket:

It is caused by pflags, we are using map[string]string as the tag field, and it is handled by pflags’s StringToStringVarP function.

https://github.com/spf13/pflag/blob/v1.0.5/string_to_string.go#L130 

https://github.com/warewulf/warewulf/blob/main/internal/pkg/node/flags.go#L223 

This function will interpret the = and , for retrieving the key and value.

A simple example to reproduce this issue

```
package main

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func main() {
	var myMapFlag map[string]string
	// Create a new cobra command
	cmd := &cobra.Command{
		Use: "my-app",
		Run: func(cmd *cobra.Command, args []string) {
			// Use the myMapFlag variable in your application
			fmt.Printf("myMapFlag: %v\n", myMapFlag)
		},
	}

	// Define a map flag using StringToStringP
	cmd.PersistentFlags().StringToStringVarP(&myMapFlag, "my-map", "m", nil, "a string map")

	// Execute the command
	if err := cmd.Execute(); err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
}
```

```
[vagrant@localhost test]$ ./example.com --my-map newtag="k1=v1,k2"
Error: invalid argument "newtag=k1=v1,k2" for "-m, --my-map" flag: k2 must be formatted as key=value
Usage:
  my-app [flags]

Flags:
  -h, --help                    help for my-app
  -m, --my-map stringToString   a string map (default [])

invalid argument "newtag=k1=v1,k2" for "-m, --my-map" flag: k2 must be formatted as key=value
```

I’d suggest either flatting the nested tags to small tags or using other symbol other than ,inside the value. 

```
wwctl profile set --yes --tagadd=Feature=standard --tagadd=CpuSpecList=1,33 default
wwctl profile set --yes --tagadd slurmdconf='Feature=standard CpuSpecList=1;33' default
```

```
[root@localhost warewulf]# cat /usr/local/etc/warewulf/nodes.conf 
WW_INTERNAL: 45
nodeprofiles:
  default:
    comment: This profile is automatically included for each node
    tags:
      CpuSpecList: 1,33
      Feature: standard
      slurmdconf: Feature=standard CpuSpecList=1;33
nodes:
  n1:
    profiles:
    - default
    network devices:
      eth0:
        onboot: "false"
        device: eth0
  n2:
    profiles:
    - default
    network devices:
      default:
        onboot: "false"
```
