### ISSUE TITLE
Add tagged VLAN interface and static route support to network devices

### ISSUE THREAD

**Issue by rthomson** [warewulf/warewulf#1257]
### Summary

Add support for configuring tagged VLAN interfaces and static routes to network devices.

### Rationale

VLAN interfaces and static routes are commonly required network configurations not currently supported by warewulf. Sites that require this functionality currently need to implement their own customize solutions.

### Description

Following the DNS resolver configuration support (https://github.com/warewulf/warewulf/issues/922), a new network device type (`vlan`) and tags can be used in combination with appropriate NetworkManger, ifcfg, wicked, etc. templates can be used to implement this functionality:

A `network devices` section in `nodes.conf` could look something like this:

```
    network devices:
      untagged:
        primary: true
        device: eth0
      tagged:
        primary: false
        type: vlan
        device: eth0.902
        tags:
          vlan_id: 902
          parent_device: eth0
          route1: "192.168.1.0/24,192.168.2.254"
```

where `untagged` and `tagged` are network devices, `vlan_id` is the tagged VLAN ID and `parent_device` is the parent network interface name of the tagged network device and `route1` is a static route definition for the `tagged` network device.

### Additional information

I have a working implementation of this in our private overlay repo but I've only implemented support for NetworkManager. Presumably warewulf should provide feature parity across all supported network configuration paradigms.

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate
