### ISSUE TITLE
Support read-only Warewulf masters for HA and multiple site support.

### ISSUE THREAD

**Issue by griznog** [warewulf/warewulf#1352]
### Summary

Support running `warewulfd` and `wwctl` in a read-only mode. With all functionality that modifies `nodes.conf` disabled the configuration can then come from an external method of distributing `nodes.conf`, node images and overlays.

### Rationale

The ability to run Warewulf in read-only mode would make it easier to have a single Warewulf master that distributes its config to multiple masters, better supporting HA setups and use of Warewulf as a multi-cluster/site infrastructure provisioning tool. 

### Description

* add a config items 
    * primary master
    * list of secondary masters
* add a flag specifying a script to call to distribute/updates to secondary servers.
* add a `wwctl config sync` command to call a sync script.

Example `warewulf.conf` entries:

```
masters:
    primary: realmaster.example.com
    secondary:
      - backupmaster.example.com
      - othersite.example.com
      - thirdsite.example.com
syncscript: `/path/to/config-sync-script.sh`
```

Leave it up to the local admin what `syncsript` will do. Methods for syncing the config might be `git`, `rsync` or some other tool for distributing it. On update a site might want to distribute the node images and overlays by any number of methods, trigger a CI/CD pipeline, trigger `wwctl container|overlay build` or any other process specific to the sites. 

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate
