### ISSUE TITLE
Add option to export with profiles resolved

### ISSUE THREAD

**Issue by jarulsamy** [warewulf/warewulf#1403]
### Summary

Using `wwctl node export` provides a limited node export. I propose we extend it with a CLI flag to make it output more information based on the profiles attached to a node. 

### Rationale

Currently, when using `wwctl node export` we can get easily get the YAML format of a node definition. This is very handy for quickly creating new/copying nodes, however it still includes profile lists. This can make it tricky to see the actual values derived from applied profiles.

For example, if I have two profiles like this:
```yaml
noselinux:
  comment: Disable selinux
  kernel:
    args: selinux=0 console=ttyS0

selinux:
  comment: Disable selinux
  kernel:
    args: console=ttyS0
```

And this typo'd node definition:

```yaml
ttest01.cluster:
  discoverable: "false"
  profiles:
  - default
  - noselinux
  - selinux
```

I would get exactly the same output for the node export command. It is often difficult to tell which profile is contributing what to a node definition directly from the exported YAML. 

### Description

I propose the addition of a `-a` (or other appropriately named flag) for the `wwctl node export` command that would output a YAML definition of the node _after_ profiles are applied. 

In this case it would be (since `selinux` gets applied after `noselinux`):

```yaml
ttest01.cluster:
  discoverable: "false"
  profiles:
  - default
  - noselinux
  - selinux
  kernel:
    args: console=ttyS0
```
This would similar to `wwctl node ls -a` which shows which profile the node is deriving a property from, but a bit more transparently. We wouldn't be able to show which profile is contributing what, but would still be able to verify the end result is correct.

Yes, I could use `wwctl node ls -a` for just verifying (me as a human operator creating new nodes). However, this is a good opportunity to allow more programmatic usage of the detailed node listings directly in YAML format. Also, I personally find the `wwctl node ls` output difficult to quickly read and decipher. I prefer to just read the raw YAML.

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate
