### ISSUE TITLE
wwctl container rename "materializes" profile container value into each node

### ISSUE THREAD

**Issue by epruesse** [warewulf/warewulf#1443]
I'm guessing that somehow `container rename` operates on the expanded node config, and writes out the new `container name` to each node, even if before it was configured at a profile level.

### Before
`nodes.conf`:
```yaml
profiles:
  gpu:
    container name: rocky-gpu
nodes:
  gpn01:
    profiles:
    - default
    - gpu
```

### Breakit
```
wwctl container rename rocky-gpu rockylinux-9-gpu
```

### After
`nodes.conf`:
```yaml
profiles:
  gpu:
    container name: rockylinux-9-gpu
nodes:
  gpn01:
    container name: rockylinux-9-gpu
    profiles:
    - default
    - gpu
```
