### ISSUE TITLE
wwctl upgrade creates false netmask entries

### ISSUE THREAD

**Issue by epruesse** [warewulf/warewulf#1661]
### Steps to reproduce

```console
wwctl upgrade nodes 
```

warewulf.conf:
```yaml
...
netmask: 255.255.240.0
...
```

nodes.conf:
```yaml
nodeprofiles:
  ...
  default
    network devices:
      default:
        type: ethernet
        device: eth0
        netmask: 255.255.240.0
nodes:
  cn001:
    network devices:
      hwaddr: aa:aa:aa:aa:aa:aa
      ipaddr: 172.16.2.1
      netmask: 255.255.255.0 # <- new entry, broke boot
``` 

### Error message

I've got `netmask 255.255.240.0` (/20) in `warewulf.conf`. The `upgrade` verb broke the `nodes.conf` by fixing "missing" netmask values using `netmask 255.255.255.0` (/24). The `netmask:` value wasn't even necessary - it's in the profile for the nodes. 

### Information on your system

4.6.0rc1
Rocky 9.5

### General information

- [x] I have run `wwctl version` and reported the contents of `/etc/os-release`
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have captured and reported relevant error messages and logs
