### ISSUE TITLE
Support list negation for arbitrary resources

### ISSUE THREAD

**Issue by Prepultrue** [warewulf/warewulf#1924]
### Summary

Similar to how kernel args, profiles, etc can have items subsequently removed by negating them `~`.
I would like to be able to remove items from arbitrary lists in node resources.

### Rationale

Say I'm using resources to control which groups end up in an `AllowGroups` entry for `sshd`.
All but a few of my nodes allow a certain group, I'd like to keep that as the default and remove that group from the list on the few nodes where it's different.

```yaml
nodeprofiles:
  default:
    # ...
    resources:
      sshd:
        allow_groups:
          - group1
nodes:
  n001:
    profiles:
      - default
    resources:
      sshd:
        allow_groups:
          - ~group1
          - group2
```

### Description

Exposing `cleanList` (from `internal/pkg/node/methods.go`) to warewulf templates would be enough, as this sidesteps the issue of "What if someone _doesn't_ want to negate items in one of their resources?".

e.g.,
```
AllowGroups {{ or (.Resources.sshd.allow_groups | cleanList | join " ") "root" }}
```

Currently, I'm using a block like below to achieve the same thing, considering there's similar logic already present internally in Warewulf, I'd rather that be exposed than duplicating this in multiple places.
```
{{ $result := list -}}
{{ $input := .Resources.sshd.allow_groups -}}
{{ range $idx, $item := $input -}}
{{   if hasPrefix "~" $item -}}
{{     continue -}}
{{   end -}}
{{   $negator := list "~" $item | join "" -}}
{{   if has $negator (slice $input (add $idx 1)) -}}
{{     continue -}}
{{   end -}}
{{ $result = append $result $item -}}
{{ end -}}
AllowGroups {{ or ($result | join " ") "root" }}
```

### General information

- [x] I have searched the issues of this repo and believe this is not a duplicate
