### ISSUE TITLE
Allow overriding compiled in paths via `warewulf.conf`

### ISSUE THREAD

**Issue by griznog** [warewulf/warewulf#635]
It'd be nice to be able to install from RPMs but still specify custom locations for the various directories used by WW. These could be specified in `warewulf.conf`, for example:

```
paths:
  overlays: /path/to/my/overlays
  chroots: /path/to/my/chroots
  provision: /path/to/my/provision
```

**Comment by anderbubble** [comment]
I would also like to see this, and would like to use it towards fixing the broken default pathing in EL right now due to overlapping upstream specfile macros.

**Comment by anderbubble** [comment]
I think these should be at

```yaml
warewulf:
  paths:
    overlays:
    chroots:
    provision:
```

@griznog can you indicate what each of these are for sake of conversation? I'm most uncertain about "provision." Is that where the built images and overlays should go?
