### ISSUE TITLE
show determined kernel version in `{{ .Kernel.Version }}`

### ISSUE THREAD

**Issue by griznog** [warewulf/warewulf#909]
### Version of Warewulf

```
# wwctl version
wwctl version:	 4.5.x-1.git_791159c
rpc version: apiPrefix:"rc1"  apiVersion:"1"  warewulfVersion:"4.5.x-1.git_791159c"
```
### Expected behavior

`{{ .Kernel.Version }}`  would resolve to the kernel version used by the container, e.g. given:

```
# wwctl container list
  CONTAINER NAME          NODES  KERNEL VERSION                CREATION TIME        MODIFICATION TIME    SIZE      
  rocky8-x86_64-current   94     4.18.0-425.19.2.el8_7.x86_64  10 Jan 22 13:06 PST  02 Sep 23 15:23 PDT  20.7 GiB  
  rocky8-x86_64-failsafe  0      4.18.0-425.19.2.el8_7.x86_64  13 Apr 23 12:48 PDT  02 Sep 23 12:45 PDT  8.0 GiB   
  rocky8-x86_64-next      3      4.18.0-477.21.1.el8_8.x86_64  10 Jan 22 13:06 PST  09 Sep 23 07:32 PDT  21.5 GiB  
```

`{{ .Kernel.Version }}` would be replaced with ` 4.18.0-477.21.1.el8_8.x86_64` for any node assigned the `rocky8-x86_64-next` container.

### Actual behavior

The value is empty, from building the `debug` overlay this section:

```
- Kernel:
  - Version: {{ .Kernel.Version }}
  - Override: {{ .Kernel.Override }}
  - Args: {{ .Kernel.Args }}
```

results in 

```
- Kernel:
  - Version: 
  - Override: 
  - Args: quiet crashkernel=no vga=791 nouveau.modeset=0 rd.driver.blacklist=nouveau
```

In the example, the node config picks up container details from a nodeprofile that sets:
```
  container-rocky8-x86_64-next:
    comment: Assign the next container image and mirrors.
    container name: rocky8-x86_64-next
    ipxe template: rocky8-x86_64-next
    system overlay:
      - system-rocky8-x86_64-next
    kernel:
      args: quiet crashkernel=no vga=791 nouveau.modeset=0 rd.driver.blacklist=nouveau
```

Setting kernel version there still results in an empty value when the template is processed..

### Steps to reproduce this behavior

Do what I describe above.

### What OS/distro are you running

Rocky 8.8

### How did you install Warewulf

Built from source not using rpms.
